// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fxlik/simple-post-api/app"
	"fxlik/simple-post-api/controller"
	"fxlik/simple-post-api/repository"
	"fxlik/simple-post-api/service"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"net/http"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	categoryRepositoryImpl := repository.NewCategoryRepositoryImpl()
	db := app.NewDB()
	validate := validator.New()
	categoryServiceImpl := service.NewCategoryServiceImpl(categoryRepositoryImpl, db, validate)
	categoryControllerImpl := controller.NewCategoryControllerImpl(categoryServiceImpl)
	levelRepositoryImpl := repository.NewLevelRepositoryImpl()
	levelServiceImpl := service.NewLevelServiceImpl(levelRepositoryImpl, db, validate)
	levelControllerImpl := controller.NewLevelControllerImpl(levelServiceImpl)
	router := app.NewRouter(categoryControllerImpl, levelControllerImpl)
	server := NewServer(router)
	return server
}

// injector.go:

var categorySet = wire.NewSet(repository.NewCategoryRepositoryImpl, wire.Bind(new(repository.CategoryRepository), new(*repository.CategoryRepositoryImpl)), service.NewCategoryServiceImpl, wire.Bind(new(service.CategoryService), new(*service.CategoryServiceImpl)), controller.NewCategoryControllerImpl, wire.Bind(new(controller.CategoryController), new(*controller.CategoryControllerImpl)))

var levelSet = wire.NewSet(repository.NewLevelRepositoryImpl, wire.Bind(new(repository.LevelRepository), new(*repository.LevelRepositoryImpl)), service.NewLevelServiceImpl, wire.Bind(new(service.LevelService), new(*service.LevelServiceImpl)), controller.NewLevelControllerImpl, wire.Bind(new(controller.LevelController), new(*controller.LevelControllerImpl)))
